### ISSUE TITLE
input fields event listener should listen to `change` 

### ISSUE THREAD

**Issue by howlowck** [billba/watchme#1]
https://github.com/billba/watchme/blob/e2c52add6579c9aea48b08506cf2ead3be342854/js.js#L130-L135

Right now the event listeners are listening to `input` which will fire every time the input of a "keyup" or paste. this could be a problem when you are changing values with a keyboard (like when you want to put from 100 to 500, and you delete the `1`, an event will fire with "00" being the value).  

Listening to `change` is generally better for form inputs, and the event fires when you click/tab away from the input or hit enter.

**Comment by billba** [comment]
I'll take that PR!
